format = """ $username\
$hostname\
$directory\
$git_branch\
$nix_shell\
$line_break\
$character"""

[directory]
style = "bold orange"
format = '\[[$path]\]($style)[$read_only]($read_only_style) '

[character]
success_symbol = " [❯](green)"
error_symbol = " [❯](red)"
vimcmd_symbol = " [❮](purple)"

[git_branch]
format = '\[[$branch]\]($style)'
style = "bright-black"

[nix_shell]
impure_msg = ''
pure_msg = ''
unknown_msg = ''
format = '\[[$name]\](yellow)'
